import './globals.css'
import { PasswordGate } from '@/components/PasswordGate'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <PasswordGate>
          {children}
        </PasswordGate>
      </body>
    </html>
  )
}
